### ISSUE TITLE
Question: it's easy to include Zink driver in your dist?

### ISSUE THREAD

**Issue by oscarbg** [pal1000/mesa-dist-win#30] opened 2020-01-31 14:53 UTC
Hi,
just forgot Zink got merged in Mesa some months ago and just curious if possible to build this driver also in your Mesa distribution.. as you know is a OpenGL 3.x driver that routes calls to underlying Vulkan driver on the system or that's the idea at least.. don't know if requires some specific Win patches or can build easily..
as said just a question, not a real need, and no pressure to integrate in case you aren't interested or it's currently unbuildable on Windows..
thanks..

**Comment by pal1000** [comment] 2020-01-31 15:49
I'll try, but I don't have much hope with it. Build most likely goes in flames as there are no automated builds for it so who knows if it even builds.

**Comment by oscarbg** [comment] 2020-02-01 14:52
thanks for trying!
seems nobody has given a try compiling Zink on MSVC.. at least these errors doesn't seem very difficult to fix.. think I will try to build when have some free time..

**Comment by pal1000** [comment] 2020-02-01 16:00
It builds successfully with MSYS2 MinGW-W64, but due to [this bug](https://gitlab.freedesktop.org/mesa/mesa/issues/2012), actually using it is a pain. That bug is the only reason I am still making mingw releases with Scons.  Obviously scons build [doesn't have zink hooked up](https://gitlab.freedesktop.org/mesa/mesa/tree/master/src/gallium/drivers/zink/SConscript) as it's in maintenance mode only until Meson bugs like this one are quashed and then will end like autotools.

**Comment by oscarbg** [comment] 2020-11-10 08:21
Hi,
just pointing out also that seems that apart from the bug you mentioned before, Zink support for Windows is being worked on and coming relatively soon..
there is a recent open issue and an early patch:
https://gitlab.freedesktop.org/zmike/mesa/-/issues/8
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7432
as pointed out in lavapipe issue, just updating issue with latest news as patch is not yet merged so support is not yet ready..
thanks..

**Comment by pal1000** [comment] 2020-11-10 09:56
I saw zink and lavapipe win32 work as well. They still have a long way to go.

**Comment by pal1000** [comment] 2020-11-12 19:00
There is a good chance to provide zink driver in MinGW package starting with 20.3 thanks to the following circumstances:
- [relevant merge request](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7432/diffs) landed shortly after 20.3 branch point;
- patch is small and targets just 1 file;
- patch applies cleanly on 20.3.0-rc1.

**Comment by pal1000** [comment] 2020-12-04 13:12
Unfortunately windows support on zink driver landed after GLonD3D12 merge which makes backporting it to 20.3 too complex

**Comment by oscarbg** [comment] 2020-12-05 22:31
thanks for the update..
it’s too much to ask for a custom zink build based on current 21.0 master then?
just a desire and can wait, as seems GL 4.6 Zink support is being merged before end of the year, and then a “special” Windows build would be desirable too..

**Comment by pal1000** [comment] 2020-12-06 10:27
> It’s too much to ask for a custom zink build based on current 21.0 master then?

No, but I need to implement a small compatibility tool to make zink work with standard Vulkan loader in addition to MSYS2 MinGW-W64 version and unfortunately due to [this bug](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3855) it's needed even when you don't use zink.
> just a desire and can wait, as seems GL 4.6 Zink support is being merged before end of the year, and then a “special” Windows build would be desirable too..

Ok.

**Comment by oscarbg** [comment] 2021-01-13 19:07
maybe it’s good time to ask for a Zink enabled Mesa 20.1.0rc1 build ? ( should have gl4.1 support)

**Comment by pal1000** [comment] 2021-01-13 21:15
I'll do both 20.3.3 and 21.0.0-rc1. Also for 21.0.0-rc1 I'll do both MSVC and MinGW builds previewing GLonD3D12 and zink respectively. zink will only be available in MinGW package and GLonD3D12 in MSVC package. They don't build the other way around.

Also these drivers introduce some regressions that I have no control over. All I can do is provide the steps and tools to workaround them.

I already mentioned the problem with zink in my previous comment that got no fix so far so I quote myself:
> No, but I need to implement a small compatibility tool to make zink work with standard Vulkan loader in addition to MSYS2 MinGW-W64 version and unfortunately due to [this bug](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3855) it's needed even when you don't use zink.

Thankfully the tool I mentioned is written [already](https://github.com/pal1000/mesa-dist-win/blob/master/bin/fix-libvulkan-1.dll-missing-error.cmd).

Then when building GLonD3D12 for the first time I had a nasty surprise. It was crashing with everything I fired at it until I learned what was [wrong](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4022). Basically you have to either disable D3D shaders signing or deploy `DXIL.dll` from Windows SDK  I personally plan to implement the latter but it still requires a do over with per-app deployment or else you get crashes. Blame Microsoft they didn't statically link DXIL somehow.

**Comment by pal1000** [comment] 2021-01-15 11:09
I did a 21.0.0-rc1 mingw release with zink and I also discovered that 32-bit is busted, opengl32.dll crashes and takes any program down with it. This regression is a last minute discovery and it's still under investigation.

**Comment by oscarbg** [comment] 2021-01-15 14:51
Hi @pal1000,
thanks for doing a zink release!
doing a quick test seems good enough.. 
for me almost these 2 issues are irrelevant for testing:
*needing a vulkan runtime loader present (I assume mosts Win PCs have it installed: current desktop GPUs and Win drivers from AMD Intel NV for almost 4.5 years have been shipping with Vulkan support and loader/runtime included)
*with your tool to fix Zink searching for libvulkan-1.dll instead of vulkan-1.dll present these bug is not affecting my testing in any way.. altough should be easy to fix in source code, right?(some #ifdef _WIN32 vulkan-1 #else libvulkan-1 #endif..

sad to hear the last minute 32 bit bug as it is preventing me of testing Unigine Heaven and Valley benchmark which would help testing Zink GL4.0 features correctly working on Windows like tesselation,arb gpu shader 5,etc ..
also Geeks3D TessMark 0.3 is a 32bit app and sadly GPUTest 0.7 requires true GL3.2 compatability profile support for any test and Zink currently supports up to GL3.0 compat profiles only.. forcing set MESA_GL_VERSION_OVERRIDE=3.2 or higher tests seems doesn't fail in checking version support and doesn't report any errors but created windows stays gray..

can close issue if wanted assuming regular builds starting with 21.0 release will have Zink support included..

**Comment by pal1000** [comment] 2021-01-15 15:39
> can close issue if wanted assuming regular builds starting with 21.0 release will have Zink support included.

Yes, they will.

**Closed by pal1000** 2021-01-15 15:39 UTC

**Comment by pal1000** [comment] 2021-01-16 21:20
I reported the x86 32-bit problem [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4108).
